### ISSUE TITLE
JSONL Support?

### ISSUE THREAD

**Issue by yukha-dw** [redis-developer/riot#101]
Hello, is there any plan to add support for JSON Lines (Line separated JSON Object)?

Example:
```
{"fieldA": 1, "fieldB": "asd"}\n
{"fieldA": 2, "fieldB": "qwe"}\n
{"fieldA": 3, "fieldB": "zxc"}\n
```

I think this format is much simpler for `riot-file` to be ingested than JSON Arrays?

**Comment by lgb861213** [comment]
Later, if the migration from elasticache for redis to elasticache for redis is tested, the tool supports JSON data. It was not supported before because the target redis does not support the JSON data type.
