### ISSUE TITLE
continuous replication problem

### ISSUE THREAD

**Issue by lgb861213** [redis-developer/riot#102]
Hi:
After testing, using this tool to migrate elasticache for redis to self-built redis cannot achieve continuous replication. The version is Redis7.0.5. Does it have anything to do with the version? Use the mode parameter and specify live or liveonly.

**Comment by jruaux** [comment]
Are the source and target running the same Redis versions? Redis 7 broke backwards compatibility for data structure serialization (which the replication process relies on through DUMP & RESTORE) but you can still use type-based replication with `replicate-ds`.

**Comment by lgb861213** [comment]
that is the source must config set notify-keyspace-events KEA
