### ISSUE TITLE
riot-file options

### ISSUE THREAD

**Issue by vliggio-tdh** [redis-developer/riot#106]
The riot-file documentation https://developer.redis.com/riot/riot-file/index.html shows two options at the end, batch and threads. These options do not exist (tried them with an =# and just # as options).

riot-file-2.19.0 % bin/riot-file --metrics -h redis-xxxcloud.redislabs.com -p 11551 -a xxxx --threads export rdb.json
Unknown option: '--threads'

riot-file-2.19.0 % bin/riot-file --metrics -h redis-xxxcloud.redislabs.com -p 11551 -a xxxx --threads export rdb.json
Unknown option: '--batch'

**Comment by jruaux** [comment]
The batch and threads options apply to commands (import, export, ...): 
riot --metrics -h redis-xxxcloud.redislabs.com -p 11551 -a xxxx file-export --threads 8 --batch rdb.json
