### ISSUE TITLE
ERR unknown command 'SCAN'

### ISSUE THREAD

**Issue by gayanW** [redis-developer/riot#111]
I'm trying to replicate data from an old standalone Redis server to a new cluster.

When I tried to do a dry run I get the following error:

```
$ ./riot -h <source> -p <port> replicate -h <target> -p <port> --dry-run
Scanning  ? % ││ 0/0 (0:00:00 / ?) ?/s
Encountered an error executing step snapshot-replication-reader in job snapshot-replication-reader: ERR unknown command 'SCAN'
Encountered an error executing step snapshot-replication in job snapshot-replication
```

The version of the source Redis is 2.6.16. I guess this error is because the SCAN command has only been available since 2.8.0.

Is there a workaround, so I could still use RIOT?

If not, I'd appreciate any ideas, and information on how to replicate such server with old Redis version.

**Comment by jruaux** [comment]
Sorry I can't think of a workaround
