### ISSUE TITLE
Can't generate more than 1000 records

### ISSUE THREAD

**Issue by ienjreny** [redis-developer/riot#113]
When we use the following command to generate random data, we get just 100 keys generated in Redis

`riot -u redis://localhost generate --count=2000`

although the output of command execution is the following

![2000](https://github.com/redis-developer/riot/assets/19180819/b954b6ce-1728-44e7-af4c-143056021f16)

The same for the following command

`riot -u redis://localhost faker-import --count=2000 id="#index" passport="passport.valid" nationality="nation.nationality" bloodType="bloodtype.bloodGroup" firstName="name.firstName" lastName="name.lastName" address="address.fullAddress" hset --keyspace person --keys id`

**Comment by jruaux** [comment]
count is for the number of iterations. The number of records is driven by the `--keys` range option which by default is 1 to 1000. I will make that key range unbounded by default so that you don't have to specify both count and keys.
