### ISSUE TITLE
Additional documentation to clarify `replicate` options

### ISSUE THREAD

**Issue by samongyr-sq** [redis-developer/riot#116]
There are a couple of interesting looking options for `replicate` that aren't documented at https://developer.redis.com/riot/

- `--event-order`
- `--flush-interval` 
- `--skip-policy` 

Some questions I was hoping the documentation would be able to answer

- `--event-order=FIFO` is self-explanatory, but it's unclear what the default (`PRIORITY`) actually means   
-  When should users consider using a different `--flush-interval`? It's unclear what this actually controls. 
- `--skip-policy=LIMIT` is the default; how does this different from the other options (e.g. `ALWAYS`, `LIMIT`)?

**Comment by jruaux** [comment]
Thanks for spotting this. Added to the 3.1.1 release documentation
