### ISSUE TITLE
Exit code when validation fails with `--mode compare`

### ISSUE THREAD

**Issue by samongyr-sq** [redis-developer/riot#117]
When using `--mode compare` to verify the `replicate` command, the command currently exits 0 even when the validation fails. 

```
$ riot "${RIOT_SOURCE[@]}" replicate "${RIOT_TARGET[@]}" --mode compare --progress ascii ; echo $?
Comparing 100% [============================================] 101/101 (0:00:00 / 0:00:00) ?/s >0 T0 ≠101 ⧗0
0
```
It would be useful to be able to force the command to exit non-zero if validation fails

**Comment by jruaux** [comment]
🎉 This issue has been resolved in `v3.1.1` ([Release Notes](https://github.com/redis-developer/riot/releases/tag/v3.1.1))
