### ISSUE TITLE
--scan-match - Is regex pattern supported ?

### ISSUE THREAD

**Issue by Sasidharan3094** [redis-developer/riot#120]
I want to match only certain prefix filter keys for example
Multiple matching prefix pattern -> `(abc:.*|def:.*)$` -> I want to match only keys starting with abc and def and the rest needs to be ignored.
Negate pattern -> `^(?!qwe:.*|rty:.*)$`  -> I want to match keys other than starting with qwe or rty.

Is this possible, I tried with this regex pattern, and seems like it is not supported. Is there any other way?

**Comment by Sasidharan3094** [comment]
@jruaux Please confirm on this

**Comment by jruaux** [comment]
🎉 This issue has been resolved in `v3.1.1` ([Release Notes](https://github.com/redis-developer/riot/releases/tag/v3.1.1))
