### ISSUE TITLE
[Question] Is possible to set an expiricy time?

### ISSUE THREAD

**Issue by ricardojudo** [redis-developer/riot#17]
One useful feature is the capability to make entries to be cleared after certain time. It would be awesome if the the expiry time could be defined for the ingested data along a riot execution. Are there any option to archive this?

**Comment by jruaux** [comment]
I have been thinking about this and it should be doable with a change in the command line syntax. I could make the redis command (HMSET for example) a repeatable subcommand of import so you could do something like this:
riot-file import beers.csv HMSET --keyspace beer --keys id EXPIRE --keyspace beer --keys id

Would that work?

**Comment by jruaux** [comment]
Hi @ricardojudo, I added this in v2.2.0. Could you give it a try and let me know if that works for you?
