### ISSUE TITLE
bigkey sync

### ISSUE THREAD

**Issue by abaowhy** [redis-developer/riot#45]
There are some bigkeys in our redis instance, which caused riot to exit abnormally, but no error was reported. The operation command is "./riot-redis -q -u redis://rc-redis.uyffb3.ng.0001.apne1.cache.amazonaws.com replicate -u redis://'xxx'@172.24.80.106:6419 --live "
![image](https://user-images.githubusercontent.com/17996343/97163712-0596ee00-17bc-11eb-866e-4278b378ab62.png)

**Comment by jruaux** [comment]
I suspect the process ran out of memory because of the big keys. What sizes are these in bytes (you can use MEMORY USAGE to report the value size)? Do you see any error at all when you run with it with --info?
