### ISSUE TITLE
riot-redis live replication does not sync keys after boot

### ISSUE THREAD

**Issue by zucaritask** [redis-developer/riot#46]
#### Context
I am trying to replicate a live redis (`redis`) instance into second one that uses ssl (`rediss`).
Whenever I start live replication with the command:

```
ubuntu@ec2:~/riot-redis-2.2.7/bin$ ./riot-redis --info -h redis_host -p 6379 --db=0 replicate -h rediss_host -p 6379 --db=0 -t --live
Opening writer
Opening reader
Replicating from redis://request1-ci.gv5c2n.ng.0001.euw1.cache.amazonaws.com?clientName=riot  ? % │█│ 54
```

If I start `rediss` with an empty key set, then after riot-redis has started, most keys have been replicated from `redis` to `rediss`. 

Running the same command with `--debug` gives me a constant stream of:

```
13:46:35.935 FINE io.lettuce.core.protocol.DefaultEndpoint	: [channel=0xdefcef92, /10.16.20.237:52564 -> rediss_host/10.16.0.30:6379, epid=0x4] flushCommands() Flushing 0 commands
```

#### Problem
After running the command and letting it run as a daemon, any subsequent write to `redis` is not replicated to `rediss` as expected by the use of `--live`.

#### Additional version info
- riot-redis: v2.2.7
- redis: 3.2.10
- redis with ssl: 3.2.6

**Comment by jruaux** [comment]
Do you have keyspace notifications enabled on the source instance? If so, do you see notifications being sent to the pubsub channel on that instance?

**Comment by zucaritask** [comment]
That was the case, thanks for your quick and specific answer. It solved my issue.
