### ISSUE TITLE
riot replication - not able run to change data capture

### ISSUE THREAD

**Issue by rkakarlapudi14** [redis-developer/riot#55]
Hello,

I am trying to get data into elastic cache from redis:-

redis version: 2.8.24
riot version:  "2.0.8"
destination: elastic cache

Using the below command i'm able to get the data into elastic cache. What seems to be happening is that only the data at the time of calling riot is getting replicated. Any incremental data written post starting riot does not get written into elastic cache. If i stop riot and re-start it seems to pick up the reminder of the keys and the same behavior continues.  Wondering if this is expected behavior ? Looking at the redis documentation looks like this might have something to do with 'notify-keyspace-events'. Also, will I need to make data changes for this work. 

Looking for more info as to why this might be happening and a possible way to solve this.

./riot-redis --info -r redis://localhost:6379 replicate -r redis://xx-redis-xx.xxxxx.ng.0001.use1.cache.amazonaws.com --live

Also, I can get riot to pull data out of elastic cache and replicate it down to my redis(reverse of my scenario above). Is there more options I need to pass to the above command for that to work?

Thanks for you time.

**Comment by jruaux** [comment]
Yes you need keyspace notifications enabled on the source Redis database in order for live replication to work, as outlined in the documentation : https://developer.redislabs.com/riot/redis/
