### ISSUE TITLE
[NEW] - Riot file command

### ISSUE THREAD

**Issue by divakaru** [redis-developer/riot#56]
I'm using riot file for uploading a CSV, but the command mentioned in the site "riot-file import http://developer.redislabs.com/riot/beers.csv --header hset --keyspace beer --keys id", having mismatched arguments for HSET

for example, below the csv format
name,designation,country
divakar,lead,india

how can I insert the above CSV into a hash, without appending any column to the key?

**Comment by jruaux** [comment]
I'm not sure I understand the problem. Could you give some details on what outcome you would like?
