### ISSUE TITLE
Generating data into a set with --max n, generates n-1 members

### ISSUE THREAD

**Issue by shkediy** [redis-developer/riot#6]
The following command:
`riot -s localhost:6379 gen --faker name=gameOfThrones.character --max 10 --command sadd --members name --keyspace got:characters`
generates 9 members.

**Comment by jruaux** [comment]
This might be because the same name is generated twice. Can you verify with the monitor command that 10 operations are actually executed?

**Comment by jruaux** [comment]
@shkediy have you been able to check the behavior above?
