### ISSUE TITLE
How to stop the live replication without using "--idle-timeout" option?

### ISSUE THREAD

**Issue by sarathyg** [redis-developer/riot#66]
We are doing live migration using this tool and need clarification on below questions
1. How to stop the live replication (MODE = LIVE) without using "--idle-timeout" option?
2. While doing live migration, if we encounter an error, whether we need to restart the process from beginning or whether it can resume from the point it encountered the error?
3. How to do verification step separately?

**Comment by jruaux** [comment]
1. You can just stop the process (kill or ctrl-C)
2. No there's no way to resume, you have to start from the beginning
3. Use the compare command (`riot-redis compare --help`

**Comment by jruaux** [comment]
I made some improvements to the comparison output. Can you give the [latest early-access](https://github.com/redis-developer/riot/releases/tag/early-access) release a try?
