### ISSUE TITLE
Live replication from EC Single -> EC Single only performs snapshot.

### ISSUE THREAD

**Issue by corymurphy** [redis-developer/riot#85]
## Description

version: riot-redis v2.15.4

I'm having an issue where live replication to and from an elasticache 5.0.3 instance only performs a snapshot, and any new keys added to the source instance don't appear to be detected on the destination instance after waiting a reasonable amount of time. (up to a couple minutes) I have also tried using elasticache 6.2.5 instances with the same behavior. 

## How to Reproduce

1. Create two Elasticache 5.0.3 instances.
1. Start riot-redis

```shell
./riot-redis/bin/riot-redis --uri redis://source:6379 \
  replicate \
  --uri redis://destination:6379 \
  --mode live
```

3. set key on source instance

```shell
redis-cli -u redis://source:6379 set mykey myvalue
OK
```

4. wait at least 5 seconds
5. get key on destination instance. This returns nil for me.

```shell
redis-cli -u redis://destination:6379 get mykey
(nil)
```

**Comment by jruaux** [comment]
Are keyspace notifications enabled on the source database?

**Comment by corymurphy** [comment]
That fixed it, thank you!
