### ISSUE TITLE
--db option saying No typeconverter registered for java.util.OptionalInt

### ISSUE THREAD

**Issue by muhil28** [redis-developer/riot#91]
No TypeConverter registered for java.util.OptionalInt of field java.util.OptionalInt com.redis.riot.RedisOptions.database
![image](https://user-images.githubusercontent.com/83505560/180206500-d97492c4-5c3b-4e71-be66-ea826ea913b2.png)

**Comment by jruaux** [comment]
Thanks for reporting this issue and for the PR. I have made another modification for the use of OptionalLong and this should be fixed in the next release.
