### ISSUE TITLE
Unable to replicate data on elasticache cluster mode enabled source

### ISSUE THREAD

**Issue by ljmendoza01** [redis-developer/riot#98]
Hi. I'm migrating data from elasticache to redis enterprise however encountered an issue when source is cluster mode is enabled.
i use this code below:
riot-redis --info --cluster -h cluster-redis-host -p 6379 replicate -h redis-enterprise-host -p 11123 --user dev-user --pass password --mode live
i'm getting this error:
Encountered an error executing step scan-reader in job scan-reader: MOVED 3392 10.00.00.16:6379
Did someone encountered the same?

**Comment by jruaux** [comment]
Hi, could you include logs around that exception?
Also, what's your Elasticache topology and connection details?

**Comment by jruaux** [comment]
What's your email address? If that works for you we could troubleshoot this via zoom

**Comment by ljmendoza01** [comment]
Update: the single quote on password field solved our issue.😅

**Comment by ljmendoza01** [comment]
update again: upon checking, not all data on our elasticache clustered source is copied to the target redis. seems like the replication command is not cluster aware. How we can solved this?
